name: Zip Files

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Make artifact directory
        run: mkdir -p ./artifacts/${{ github.repository }}
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: test/hello.py
          dest: ./artifacts/result.zip
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: ./artifacts

