name: Zip Files

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: test/hello.py
          dest: result.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: /home/runner/work/actionstest/actionstest/result.zip


  deploy:
    needs: zip-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
   
      - name: Upload file to bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: /home/runner/work/actionstest/actionstest/result.zip
          AWS_REGION: 'eu-west-2'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

