name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOYMENT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOYMENT_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M')"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create file name
        id: filename
        run: echo "::set-output name=filename::${{ steps.vars.outputs.date }}_${{ github.event.repository.name }}_${{ steps.tag_version.outputs.new_tag }}_${{ steps.vars.outputs.sha_short }}.zip"
      - name: Make artifact directory
        run: mkdir -p ./artifacts
      - uses: papeloto/action-zip@v1
        with:
          files: /
          dest: ./artifacts/${{ steps.filename.outputs.filename }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: ./artifacts/${{ steps.filename.outputs.filename }}
      - name: Upload artifacts to S3 - Developer Triggered
        run: python upload_artifacts_to_s3.py ${{ secrets.AWS_S3_RELEASE_BUCKET }} ${{ steps.filename.outputs.filename }} ${{ github.event.repository.name }}
